// Generated by nuxi
/// <reference types="@nuxtjs/vuetify" />
/// <reference types="@nuxt/bridge-edge" />
/// <reference types="@nuxtjs/axios" />
/// <reference types="@nuxt/components" />
/// <reference types="@nuxt/telemetry" />
/// <reference path="nitro.d.ts" />
/// <reference path="components.d.ts" />
/// <reference types="unplugin-vue2-script-setup/types" />
/// <reference path="auto-imports.d.ts" />
/// <reference path="imports.d.ts" />

export {}
